# Generated by Django 3.0.1 on 2020-01-24 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trips_name', models.CharField(max_length=50)),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_main', models.ImageField(blank=True, upload_to='images/')),
                ('name_travel', models.CharField(max_length=50)),
                ('price_travel', models.IntegerField()),
                ('description_travel', models.TextField()),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('trips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Trips')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=50, verbose_name='Ваше имя:')),
                ('user_comment', models.TextField(verbose_name='Текст:')),
                ('comment_travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='tours.Travel')),
            ],
        ),
    ]
