# Generated by Django 3.0.1 on 2020-02-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_aboutUs', models.ImageField(blank=True, upload_to='images_aboutUs/')),
                ('description_aboutUs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_employee', models.ImageField(blank=True, upload_to='photo_employee/')),
                ('name_employee', models.CharField(max_length=50)),
                ('description_employee', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('name_trips', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='travel',
            name='video_travel',
            field=models.FileField(blank=True, upload_to='video_travel/'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_travel', models.ImageField(blank=True, upload_to='images_carusel/')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel', to='tours.Travel')),
            ],
        ),
    ]
