# Generated by Django 3.0.1 on 2020-02-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20200222_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='name_trips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nametrips', to='tours.Travel'),
        ),
    ]
