# Generated by Django 3.0.1 on 2020-03-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20200222_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='departure_date',
            field=models.DateField(blank='True'),
        ),
    ]
