# Generated by Django 3.0.1 on 2020-03-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20200302_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='name_trips',
        ),
        migrations.AddField(
            model_name='timetable',
            name='name_trips',
            field=models.ManyToManyField(to='tours.Travel'),
        ),
    ]
