# Generated by Django 3.0.1 on 2020-03-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20200306_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='tel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
